/* ast node 가 표현할 수 있는 풀의 타입*/
export default {
    BOOL: 'BOOL',
    IDENTIFIER: 'IDENTIFIER',
    INTEGER_LITERAL: 'INTEGER_LITERAL',
    FUNCTION_EXPRESSION: 'FUNCTION_EXPRESSION',
    IF_EXPRESSION: 'IF_EXPRESSION',
    INFIX_EXPRESSION: 'INFIX_EXPRESSION',
    CALL_EXPRESSION: 'CALL_EXPRESSION',
    PREFIX_EXPRESSION: 'PREFIX_EXPRESSION',
    LET_STATEMENT: 'LET_STATEMENT',
    BLOCK_STATEMENT: 'BLOCK_STATEMENT',
    EXPRESSION_STATEMENT: 'EXPRESSION_STATEMENT',
    RETURN_STATEMENT: 'RETURN_STATEMENT',
    PROGRAM: 'PROGRAM',
};