export default {
    ILLEGAL: 'ILLEGAL',
    EOF: 'EOF',
    IDENT: 'IDENT',
    INT: 'INT',
    ASSIGN: '=',
    PLUS: '+',
    MINUS: '-',
    BANG: '!',
    ASTERISK: '*',
    SLASH: '/',
    LT: '<',
    GT: '>',
    COMMA: ',',
    SEMICOLON: ';',
    LPAREN: '(',
    RPAREN: ')',
    RBRACE: '}',
    LBRACE: '{',
    FUNCTION: 'FUNCTION',
    LET: 'LET',
    TRUE: 'TRUE',
    FALSE: 'FALSE',
    IF: 'IF',
    ELSE: 'ELSE',
    RETURN: 'RETURN',
};
